from KiemThu import *
from time import *

# print(ChieuDai(mang_so_1))
# print(ChieuDai(ds_so_1))
# print(ChieuDai(mang_chu_1))
# print(DaySo(0, 11))
# print(DaySo(0, 11, 0.5))
# print(DaySo(0, 11, 2))
# print(DaySo(10, -1, -1))
# print(ChieuDai(mang_so_2))
# print(ChieuDai(so_1))
# print(Noi([], [0]))
# print(Noi(1,[1,2,3]))
# print(Noi([1],[1,2,3]))
# print(Tong([1,2,3]))
# print(LonNhat(mang_chu_1))
# print(LonNhat(mang_so_2))
print(mang_so_3)
#--------------------------------
bat_dau = time()
print(LonNhat(mang_so_3))
print(NhoNhat(mang_so_3))
#print(DaoNguoc(mang_so_3))
ket_thuc = time()
print('Thoi gian chay (ms): ', (ket_thuc - bat_dau) * 1000)
#--------------------------------
bat_dau = time()
print(max(mang_so_3))
print(min(mang_so_3))
# mang_so_3.reverse()
# print(mang_so_3)
ket_thuc = time()
print('Thoi gian chay (ms): ', (ket_thuc - bat_dau) * 1000)
#--------------------------------