from KiemThu import *

# print(ChieuDai(mang_so_1))
# print(ChieuDai(ds_so_1))
# print(ChieuDai(mang_chu_1))
# print(DaySo(0, 11))
# print(DaySo(0, 11, 0.5))
# print(DaySo(0, 11, 2))
# print(DaySo(10, -1, -1))
# print(ChieuDai(mang_so_2))
# print(ChieuDai(so_1))
# print(Noi([], [0]))
# print(Noi(1,[1,2,3]))
# print(Noi([1],[1,2,3]))
# print(Tong([1,2,3]))
# print(LonNhat(mang_chu_1))
# print(LonNhat(mang_so_2))
print(mang_so_3)
print(LonNhat(mang_so_3))